# Generated by Django 4.0.6 on 2022-11-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('instrument', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('number_stars', models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Good'), (4, 'Excellent')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_form.musicianmodel')),
            ],
        ),
    ]
